AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

Metrics/LineLength:
  Max: 120


Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%w': '[]'

Rails/HasAndBelongsToMany:
  Enabled: false

Style/AndOr:
  Exclude:
    - 'app/controllers/**/*'

Style/SingleLineBlockParams:
  Enabled: false
