default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: adventure_glass_dev

test:
  <<: *default
  database: adventure_glass_test

production:
  <<: *default
  database: adventure_glass_prod
